<?php
/**
 * TSO Swiss Knife – Module: Server Files Review.
 *
 * Reviews robots.txt and .htaccess. Also detects sitemap XML files
 * generated by popular plugins. Supports inline editing.
 *
 * @package TSO_Swiss_Knife
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TSOSK_Mod_Server_Files {

	private static $instance = null;

	public static function get_instance(): self {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
		add_action( 'wp_ajax_tsosk_sf_save', array( $this, 'ajax_save' ) );
	}

	/** AJAX: save an editable file. */
	public function ajax_save(): void {
		check_ajax_referer( 'tsosk_sf_nonce', 'nonce' );
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Insufficient permissions.', 'tso-swiss-knife' ), 403 );
		}

		$key     = isset( $_POST['key'] ) ? sanitize_key( wp_unslash( $_POST['key'] ) ) : '';
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- server config file content must not be sanitized; any alteration could corrupt .htaccess or robots.txt directives.
		$content = isset( $_POST['content'] ) ? wp_unslash( $_POST['content'] ) : '';

		$allowed_keys = array( 'robots', 'robots_local', 'htaccess', 'htaccess_root' );
		if ( ! in_array( $key, $allowed_keys, true ) ) {
			wp_send_json_error( __( 'Invalid file key.', 'tso-swiss-knife' ) );
		}

		// phpcs:ignore PluginCheck.CodeAnalysis.WriteFile.ABSPATHDetected -- robots.txt and .htaccess are server-root files that must be written at ABSPATH; wp_upload_dir() is not appropriate for these.
		// robots → domain root; robots_local → WP subdirectory; htaccess → ABSPATH; htaccess_root → document root.
		if ( 'robots' === $key ) {
			$path = $this->root_robots_path();
		} elseif ( 'robots_local' === $key ) {
			$path = ABSPATH . 'robots.txt';
		} elseif ( 'htaccess_root' === $key ) {
			$path = $this->root_htaccess_path();
		} else {
			$path = ABSPATH . '.htaccess';
		}

		if ( ! wp_is_writable( $path ) && ! wp_is_writable( dirname( $path ) ) ) {
			wp_send_json_error( __( 'File is not writable.', 'tso-swiss-knife' ) );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents, PluginCheck.CodeAnalysis.WriteFile.ABSPATHDetected -- robots.txt and .htaccess must be written at the server root; wp_upload_dir() is not appropriate for these system files.
		$result = file_put_contents( $path, $content );
		if ( false === $result ) {
			wp_send_json_error( __( 'Could not save the file.', 'tso-swiss-knife' ) );
		}

		TSOSK_Activity_Log::log(
			'server-files',
			'save',
			sprintf(
				/* translators: %s: file key */
				__( 'Server file saved: %s.', 'tso-swiss-knife' ),
				$key
			),
			array( 'file' => $key )
		);

		wp_send_json_success( __( 'File saved.', 'tso-swiss-knife' ) );
	}

	/** Detect the robots.txt path (may be in public_html parent or ABSPATH). */
	/**
	 * Find the robots.txt at the domain root (the one Google actually reads).
	 *
	 * Strategy: walk UP from ABSPATH until we reach the server document root,
	 * looking for robots.txt at each level. Falls back to $_SERVER['DOCUMENT_ROOT']
	 * if available.
	 *
	 * @return string Absolute path to root robots.txt (may not exist yet).
	 */
	private function root_robots_path(): string {
		// 1. Try document root directly.
		$doc_root = isset( $_SERVER['DOCUMENT_ROOT'] )
			? rtrim( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '/' )
			: '';

		if ( $doc_root && file_exists( $doc_root . '/robots.txt' ) ) {
			return $doc_root . '/robots.txt';
		}

		// 2. Walk up from ABSPATH (max 5 levels) looking for robots.txt.
		$dir    = untrailingslashit( ABSPATH );
		$levels = 0;
		while ( $levels < 5 ) {
			if ( file_exists( $dir . '/robots.txt' ) ) {
				return $dir . '/robots.txt';
			}
			$parent = dirname( $dir );
			if ( $parent === $dir ) {
				break; // Reached filesystem root.
			}
			$dir = $parent;
			$levels++;
		}

		// 3. Return document root path as the "create here" destination.
		if ( $doc_root ) {
			return $doc_root . '/robots.txt';
		}

		// 4. Last fallback.
		return ABSPATH . 'robots.txt';
	}

	/**
	 * Find the local robots.txt inside the WordPress install subdirectory.
	 * Returns empty string if WP is at the domain root (root and local are the same).
	 *
	 * @return string Absolute path, or empty string.
	 */
	private function local_robots_path(): string {
		$root_path  = $this->root_robots_path();
		$local_path = ABSPATH . 'robots.txt';

		// If they resolve to the same directory, there's no separate "local" file.
		if ( realpath( dirname( $root_path ) ) === realpath( ABSPATH ) ) {
			return '';
		}

		// Only return if file actually exists (don't offer to create it — misleading).
		return file_exists( $local_path ) ? $local_path : '';
	}

	/**
	 * Find the .htaccess at the domain document root (parent of a subdirectory install).
	 *
	 * @return string Absolute path (may not exist yet).
	 */
	private function root_htaccess_path(): string {
		$doc_root = isset( $_SERVER['DOCUMENT_ROOT'] )
			? rtrim( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '/' )
			: '';

		if ( $doc_root ) {
			return $doc_root . '/.htaccess';
		}

		$dir    = untrailingslashit( ABSPATH );
		$levels = 0;
		while ( $levels < 5 ) {
			$parent = dirname( $dir );
			if ( $parent === $dir ) {
				break;
			}
			if ( file_exists( $parent . '/.htaccess' ) && realpath( $parent ) !== realpath( ABSPATH ) ) {
				return $parent . '/.htaccess';
			}
			$dir = $parent;
			$levels++;
		}

		return ABSPATH . '.htaccess';
	}

	/**
	 * WordPress install .htaccess path (pretty permalinks).
	 *
	 * @return string
	 */
	private function local_htaccess_path(): string {
		return ABSPATH . '.htaccess';
	}

	/**
	 * Whether WP runs in a subdirectory (root files differ from ABSPATH).
	 *
	 * @return bool
	 */
	private function wp_is_subdirectory_install(): bool {
		$root_dir  = realpath( dirname( $this->root_htaccess_path() ) );
		$local_dir = realpath( ABSPATH );
		return $root_dir && $local_dir && $root_dir !== $local_dir;
	}

	/**
	 * BC alias used in detect_sitemaps() for robots.txt content.
	 *
	 * @return string
	 */
	private function robots_path(): string {
		return $this->root_robots_path();
	}

	/** Detect sitemap files from popular plugins. */
	private function detect_sitemaps(): array {
		$sitemaps = array();
		$abspath  = trailingslashit( ABSPATH );

		// Build a helper: known plugin slug → plugin name + sitemap URL pattern
		$known_plugins = array(
			// XML Sitemap Generator for Google (Auctollo) — multiple known slugs
			'google-sitemap-generator/sitemap.php'         => 'XML Sitemap Generator for Google',
			'googlesitemaps/sitemap.php'                    => 'XML Sitemap Generator for Google',
			'google-sitemap-generator/google-sitemap-generator.php' => 'XML Sitemap Generator for Google',
			// Yoast SEO
			'wordpress-seo/wp-seo.php'                     => 'Yoast SEO',
			'wordpress-seo-premium/wp-seo-premium.php'     => 'Yoast SEO Premium',
			// All in One SEO
			'all-in-one-seo-pack/all_in_one_seo_pack.php'  => 'All in One SEO',
			'aioseo/aioseo.php'                            => 'All in One SEO (Pro)',
			// Rank Math
			'seo-by-rank-math/rank-math.php'               => 'Rank Math SEO',
			'seo-by-rank-math-pro/rank-math-pro.php'       => 'Rank Math SEO Pro',
			// The SEO Framework
			'autodescription/autodescription.php'          => 'The SEO Framework',
			// SEOPress
			'wp-seopress/seopress.php'                     => 'SEOPress',
			'wp-seopress-pro/seopress-pro.php'             => 'SEOPress Pro',
			// Slim SEO
			'slim-seo/slim-seo.php'                        => 'Slim SEO',
			// XML Sitemap & Google News
			'xml-sitemap-feed/xml-sitemap.php'             => 'XML Sitemap & Google News',
			// Jetpack (has sitemap)
			'jetpack/jetpack.php'                          => 'Jetpack',
		);

		// Which active plugins are actually sitemaps-capable?
		$active = (array) get_option( 'active_plugins', array() );
		$active_seo = array();
		foreach ( $active as $plugin_file ) {
			if ( isset( $known_plugins[ $plugin_file ] ) ) {
				$active_seo[ $plugin_file ] = $known_plugins[ $plugin_file ];
			}
		}

		$already_urls = array(); // Track URLs added to avoid duplicates

		// Helper closure to add without duplicate
		$add = function( array $entry ) use ( &$sitemaps, &$already_urls ) {
			$key = rtrim( $entry['url'], '/' );
			if ( ! in_array( $key, $already_urls, true ) ) {
				$sitemaps[]     = $entry;
				$already_urls[] = $key;
			}
		};

		// ── 1. WordPress Core Sitemap (built-in since WP 5.5) ─────────────────
		// Only show if NOT disabled by a plugin or filter.
		// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound -- WordPress core filter.
		$core_disabled = ! apply_filters( 'wp_sitemaps_enabled', true );
		if ( ! $core_disabled ) {
			$add( array(
				'label'  => 'WordPress Core Sitemap',
				'url'    => home_url( '/wp-sitemap.xml' ),
				'path'   => '',
				'exists' => true,
				'plugin' => 'WordPress',
				'type'   => 'virtual',
			) );
		}

		// ── 2. Yoast SEO ──────────────────────────────────────────────────────
		$yoast_active = isset( $active_seo['wordpress-seo/wp-seo.php'] ) ||
		               isset( $active_seo['wordpress-seo-premium/wp-seo-premium.php'] );
		$yoast_index  = $abspath . 'sitemap_index.xml';
		if ( $yoast_active || file_exists( $yoast_index ) ) {
			$plugin_name = $active_seo['wordpress-seo-premium/wp-seo-premium.php'] ?? ( $active_seo['wordpress-seo/wp-seo.php'] ?? 'Yoast SEO' );
			$add( array(
				'label'  => $plugin_name . ' Sitemap (sitemap_index.xml)',
				'url'    => home_url( '/sitemap_index.xml' ),
				'path'   => $yoast_index,
				'exists' => $yoast_active || file_exists( $yoast_index ),
				'plugin' => $plugin_name,
				'type'   => file_exists( $yoast_index ) ? 'physical' : 'virtual',
			) );
		}

		// ── 3. XML Sitemap Generator for Google (Auctollo) ────────────────────
		$auctollo_active = isset( $active_seo['google-sitemap-generator/sitemap.php'] ) ||
		                  isset( $active_seo['googlesitemaps/sitemap.php'] ) ||
		                  isset( $active_seo['google-sitemap-generator/google-sitemap-generator.php'] );
		$auctollo_paths = array(
			$abspath . 'sitemap.xml',
			$abspath . 'sitemap.xml.gz',
			$abspath . 'sitemap-index.xml',
		);
		foreach ( $auctollo_paths as $p ) {
			if ( file_exists( $p ) ) {
				$add( array(
					'label'  => 'XML Sitemap Generator for Google (' . basename( $p ) . ')',
					'url'    => home_url( '/' . basename( $p ) ),
					'path'   => $p,
					'exists' => true,
					'plugin' => 'XML Sitemap Generator for Google',
					'type'   => 'physical',
				) );
				break;
			}
		}
		if ( $auctollo_active ) {
			// Plugin is active → always show even if file not yet generated.
			$url_candidate = home_url( '/sitemap.xml' );
			if ( ! in_array( rtrim( $url_candidate, '/' ), $already_urls, true ) ) {
				$add( array(
					'label'  => 'XML Sitemap Generator for Google (sitemap.xml)',
					'url'    => $url_candidate,
					'path'   => $abspath . 'sitemap.xml',
					'exists' => file_exists( $abspath . 'sitemap.xml' ),
					'plugin' => 'XML Sitemap Generator for Google',
					'type'   => 'virtual',
				) );
			}
		}

		// ── 4. All in One SEO ─────────────────────────────────────────────────
		$aioseo_active = isset( $active_seo['all-in-one-seo-pack/all_in_one_seo_pack.php'] ) ||
		               isset( $active_seo['aioseo/aioseo.php'] );
		if ( $aioseo_active ) {
			$plugin_name = $active_seo['aioseo/aioseo.php'] ?? 'All in One SEO';
			$add( array(
				'label'  => $plugin_name . ' Sitemap (sitemap.xml)',
				'url'    => home_url( '/sitemap.xml' ),
				'path'   => '',
				'exists' => true,
				'plugin' => $plugin_name,
				'type'   => 'virtual',
			) );
		}

		// ── 5. Rank Math ──────────────────────────────────────────────────────
		$rankmath_active = isset( $active_seo['seo-by-rank-math/rank-math.php'] ) ||
		                  isset( $active_seo['seo-by-rank-math-pro/rank-math-pro.php'] );
		if ( $rankmath_active ) {
			$plugin_name = $active_seo['seo-by-rank-math-pro/rank-math-pro.php'] ?? 'Rank Math SEO';
			$add( array(
				'label'  => $plugin_name . ' Sitemap (sitemap_index.xml)',
				'url'    => home_url( '/sitemap_index.xml' ),
				'path'   => '',
				'exists' => true,
				'plugin' => $plugin_name,
				'type'   => 'virtual',
			) );
		}

		// ── 6. Other SEO plugins with known sitemap URLs ──────────────────────
		$other_seo = array(
			'autodescription/autodescription.php' => array( 'url' => home_url( '/sitemap.xml' ) ),
			'wp-seopress/seopress.php'            => array( 'url' => home_url( '/seopress-sitemap.xml' ) ),
			'wp-seopress-pro/seopress-pro.php'    => array( 'url' => home_url( '/seopress-sitemap.xml' ) ),
			'slim-seo/slim-seo.php'               => array( 'url' => home_url( '/sitemap.xml' ) ),
			'xml-sitemap-feed/xml-sitemap.php'    => array( 'url' => home_url( '/sitemap.xml' ) ),
		);
		foreach ( $other_seo as $plugin_file => $data ) {
			if ( isset( $active_seo[ $plugin_file ] ) ) {
				$plugin_name = $known_plugins[ $plugin_file ];
				$add( array(
					'label'  => $plugin_name . ' Sitemap',
					'url'    => $data['url'],
					'path'   => '',
					'exists' => true,
					'plugin' => $plugin_name,
					'type'   => 'virtual',
				) );
			}
		}

		// ── 7. Sitemap directives in robots.txt ───────────────────────────────
		// For each URL found, try to identify which plugin owns it.
		$robots_path = $this->robots_path();
		if ( file_exists( $robots_path ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			$robots_content = (string) file_get_contents( $robots_path );
			preg_match_all( '/^Sitemap\s*:\s*(\S+)/im', $robots_content, $matches_rb );
			foreach ( $matches_rb[1] as $url ) {
				$url = trim( $url );
				if ( in_array( rtrim( $url, '/' ), $already_urls, true ) ) {
					continue; // Already identified by plugin detection above.
				}
				// Try to attribute the URL to a known plugin by path pattern.
				$attributed_plugin = $this->attribute_sitemap_url( $url, $known_plugins );
				// Detect if file exists physically (strip WP install subdirectory from URL path).
				$u_path    = (string) wp_parse_url( $url, PHP_URL_PATH );
				$site_path = (string) wp_parse_url( site_url(), PHP_URL_PATH );
				$site_path = trailingslashit( $site_path );
				$rel       = ( '/' === $site_path )
					? $u_path
					: str_replace( rtrim( $site_path, '/' ), '', $u_path );
				$local     = ABSPATH . ltrim( $rel, '/' );
				$physical  = file_exists( $local );
				$add( array(
					'label'  => basename( $u_path ) . ' (robots.txt)',
					'url'    => $url,
					'path'   => $physical ? $local : '',
					'exists' => true,
					'plugin' => $attributed_plugin,
					'type'   => $physical ? 'physical' : 'virtual',
				) );
			}
		}

		// ── HTTP verification: check each URL returns 200 ──────────────────────
		// Uses wp_remote_head() with a short timeout (5s) to avoid slowing the page.
		// Physical files are assumed reachable; only virtual URLs need checking.
		foreach ( $sitemaps as &$entry ) {
			if ( 'physical' === $entry['type'] ) {
				$entry['http_status'] = 200;
			} else {
				$response = wp_remote_head( $entry['url'], array(
					'timeout'    => 5,
					'sslverify'  => false,
					'user-agent' => 'TSO Swiss Knife Sitemap Checker/1.0',
				) );
				if ( is_wp_error( $response ) ) {
					$entry['http_status'] = 0;
				} else {
					$entry['http_status'] = (int) wp_remote_retrieve_response_code( $response );
				}
			}
		}
		unset( $entry );

		// Remove entries that return 404 or connection error, unless they are physical files.
		$sitemaps = array_values( array_filter( $sitemaps, static function ( array $e ): bool {
			// Always keep physical files (they exist on disk).
			if ( 'physical' === $e['type'] ) { return true; }
			// Keep if HTTP check succeeded (2xx) or was not checked (status 0 = connection error shown as warning).
			return $e['http_status'] !== 404;
		} ) );

		return $sitemaps;
	}

	/**
	 * Try to identify which plugin owns a sitemap URL by its path patterns.
	 *
	 * @param string               $url          Sitemap URL.
	 * @param array<string,string> $known_plugins Map of plugin_file → plugin_name.
	 * @return string Plugin name or "Unknown plugin".
	 */
	private function attribute_sitemap_url( string $url, array $known_plugins ): string {
		$path   = strtolower( (string) wp_parse_url( $url, PHP_URL_PATH ) );
		$active = (array) get_option( 'active_plugins', array() );

		// ── WordPress core sitemap ────────────────────────────────────────────
		if ( false !== strpos( $path, 'wp-sitemap' ) ) {
			return 'WordPress Core';
		}

		// ── Exact-slug priority matches ───────────────────────────────────────
		// URL-pattern → ordered list of plugin file slugs to try.
		$priority = array(
			'sitemap_index.xml' => array(
				'wordpress-seo/wp-seo.php',
				'wordpress-seo-premium/wp-seo-premium.php',
				'seo-by-rank-math/rank-math.php',
				'seo-by-rank-math-pro/rank-math-pro.php',
			),
			'seopress-sitemap' => array(
				'wp-seopress/seopress.php',
				'wp-seopress-pro/seopress-pro.php',
			),
		);
		foreach ( $priority as $pattern => $slugs ) {
			if ( false !== strpos( $path, $pattern ) ) {
				foreach ( $slugs as $slug ) {
					if ( in_array( $slug, $active, true ) ) {
						return $known_plugins[ $slug ] ?? $slug;
					}
				}
			}
		}

		// ── Physical file check (works even if URL has WP install subdirectory) ─
		// Strip the WP site path prefix from the URL path to get a server-root-relative path.
		$site_path   = trailingslashit( (string) wp_parse_url( site_url(), PHP_URL_PATH ) );
		$rel_path    = '/' === $site_path ? $path : str_replace( rtrim( $site_path, '/' ), '', $path );
		$local_check = ABSPATH . ltrim( $rel_path, '/' );
		$file_exists = file_exists( $local_check );

		// ── Generic sitemap.xml / sitemap-*.xml matching ──────────────────────
		if ( false !== strpos( $path, 'sitemap' ) ) {
			// If the physical file exists, Auctollo (XML Sitemap Generator) is the most
			// likely candidate since it writes a physical file; others use virtual URLs.
			if ( $file_exists ) {
				$auctollo_slugs = array(
					'google-sitemap-generator/sitemap.php',
					'googlesitemaps/sitemap.php',
					'google-sitemap-generator/google-sitemap-generator.php',
				);
				foreach ( $auctollo_slugs as $slug ) {
					if ( in_array( $slug, $active, true ) ) {
						return 'XML Sitemap Generator for Google';
					}
				}
				return 'XML Sitemap Generator for Google';
			}

			// No physical file → try every known active plugin by slug prefix match.
			// This covers installs where the plugin slug is different from our list.
			$slug_keywords = array(
				'google-sitemap'  => 'XML Sitemap Generator for Google',
				'googlesitemap'   => 'XML Sitemap Generator for Google',
				'xml-sitemap'     => 'XML Sitemap Generator for Google',
				'wordpress-seo'   => 'Yoast SEO',
				'all-in-one-seo'  => 'All in One SEO',
				'aioseo'          => 'All in One SEO',
				'rank-math'       => 'Rank Math SEO',
				'seopress'        => 'SEOPress',
				'slim-seo'        => 'Slim SEO',
				'jetpack'         => 'Jetpack',
			);
			foreach ( $active as $plugin_file ) {
				$folder = strtolower( explode( '/', $plugin_file )[0] );
				foreach ( $slug_keywords as $keyword => $name ) {
					if ( false !== strpos( $folder, $keyword ) ) {
						return $name;
					}
				}
			}

			// Last resort: any active plugin whose folder contains 'sitemap'.
			foreach ( $active as $plugin_file ) {
				if ( false !== strpos( strtolower( $plugin_file ), 'sitemap' ) ) {
					// Return the plugin Display Name if we know it, else the folder slug.
					$folder = explode( '/', $plugin_file )[0];
					return $known_plugins[ $plugin_file ] ?? $folder;
				}
			}
		}

		return __( 'Unknown plugin', 'tso-swiss-knife' );
	}

	public function render(): void {
		$nonce = wp_create_nonce( 'tsosk_sf_nonce' );

		$root_robots  = $this->root_robots_path();
		$local_robots = $this->local_robots_path();
		$wp_is_subdir = $this->wp_is_subdirectory_install() || (
			'' !== $local_robots || realpath( dirname( $root_robots ) ) !== realpath( ABSPATH )
		);

		$reports = array();

		// Always show the domain-root robots.txt first.
		$reports['robots'] = $this->get_report( 'robots.txt (domain root)', $root_robots, 'robots' );
		$reports['robots']['is_root']   = true;
		$reports['robots']['root_note'] = $wp_is_subdir;

		// If WordPress is in a subdirectory, also show the local robots.txt.
		if ( $wp_is_subdir && '' !== $local_robots ) {
			$reports['robots_local'] = $this->get_report( 'robots.txt (WordPress subdirectory)', $local_robots, 'robots_local' );
			$reports['robots_local']['is_root']   = false;
			$reports['robots_local']['root_note'] = true;
		}

		$root_htaccess  = $this->root_htaccess_path();
		$local_htaccess = $this->local_htaccess_path();
		$same_htaccess  = realpath( dirname( $root_htaccess ) ) === realpath( ABSPATH );

		if ( ! $same_htaccess ) {
			$reports['htaccess_root'] = $this->get_report( __( '.htaccess (domain / document root)', 'tso-swiss-knife' ), $root_htaccess, 'htaccess_root' );
			$reports['htaccess_root']['is_root']   = true;
			$reports['htaccess_root']['is_htaccess'] = true;
		}

		$reports['htaccess'] = $this->get_report(
			$same_htaccess ? __( '.htaccess', 'tso-swiss-knife' ) : __( '.htaccess (WordPress subdirectory)', 'tso-swiss-knife' ),
			$local_htaccess,
			'htaccess'
		);
		if ( ! $same_htaccess ) {
			$reports['htaccess']['is_root']      = false;
			$reports['htaccess']['is_htaccess']  = true;
			$reports['htaccess']['root_note']    = true;
		}
		$sitemaps = $this->detect_sitemaps();
		?>
		<p class="tsosk-desc">
			<?php esc_html_e( 'Review and edit the server configuration files that control crawling, permalinks and redirects. On subdirectory installs (e.g. /blogbkp2/), Apache may use a root .htaccess in public_html plus a separate one inside WordPress. Also shows all sitemap files detected on this installation.', 'tso-swiss-knife' ); ?>
		</p>

		<?php foreach ( $reports as $key => $report ) : ?>
			<?php $this->render_report( $key, $report, $nonce ); ?>
		<?php endforeach; ?>

		<?php /* ── Sitemaps ── */ ?>
		<div class="tsosk-card">
			<h3><?php esc_html_e( 'Sitemaps', 'tso-swiss-knife' ); ?></h3>
			<p class="description">
				<?php esc_html_e( 'Sitemaps are files that list all the pages on your website so that search engines like Google can find them more easily. This panel detects sitemaps generated by popular SEO plugins.', 'tso-swiss-knife' ); ?>
			</p>
			<table class="widefat tsosk-table">
				<thead><tr>
					<th><?php esc_html_e( 'Sitemap', 'tso-swiss-knife' ); ?></th>
					<th><?php esc_html_e( 'Plugin', 'tso-swiss-knife' ); ?></th>
					<th><?php esc_html_e( 'Type', 'tso-swiss-knife' ); ?></th>
					<th><?php esc_html_e( 'URL', 'tso-swiss-knife' ); ?></th>
				</tr></thead>
				<tbody>
				<?php foreach ( $sitemaps as $s ) :
					$http  = (int) ( $s['http_status'] ?? 0 );
					$is_ok = 'physical' === $s['type'] || ( $http >= 200 && $http < 300 );
				?>
					<tr<?php echo ! $is_ok ? ' style="opacity:.55;"' : ''; ?>>
						<td><?php echo esc_html( $s['label'] ); ?></td>
						<td><?php echo esc_html( $s['plugin'] ); ?></td>
						<td>
							<?php if ( 'physical' === $s['type'] ) : ?>
								<span class="tsosk-badge tsosk-badge-ok"><?php esc_html_e( 'Physical file', 'tso-swiss-knife' ); ?></span>
							<?php else : ?>
								<span class="tsosk-badge tsosk-badge-info"><?php esc_html_e( 'Virtual (plugin)', 'tso-swiss-knife' ); ?></span>
							<?php endif; ?>
						</td>
						<td>
							<?php if ( $is_ok ) : ?>
								<a href="<?php echo esc_url( $s['url'] ); ?>" target="_blank" rel="noopener noreferrer">
									<?php echo esc_html( $s['url'] ); ?>
								</a>
								<?php if ( $http > 0 ) : ?>
								<span class="tsosk-badge tsosk-badge-ok" style="font-size:10px;margin-left:6px;">HTTP <?php echo esc_html( (string) $http ); ?></span>
								<?php endif; ?>
							<?php else : ?>
								<span style="color:#8c8f94;text-decoration:line-through;font-size:12px;"><?php echo esc_html( $s['url'] ); ?></span>
								<span class="tsosk-badge tsosk-badge-warn" style="font-size:10px;margin-left:6px;">
									HTTP <?php echo $http > 0 ? esc_html( (string) $http ) : esc_html__( 'error', 'tso-swiss-knife' ); ?>
								</span>
							<?php endif; ?>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<?php
	}

	private function get_report( string $label, string $path, string $key ): array {
		$report = array(
			'label'    => $label,
			'path'     => $path,
			'key'      => $key,
			'exists'   => file_exists( $path ),
			'readable' => is_readable( $path ),
			'writable' => file_exists( $path ) && wp_is_writable( $path ),
			'size'     => file_exists( $path ) ? (int) filesize( $path ) : 0,
			'modified' => file_exists( $path ) ? (int) filemtime( $path ) : 0,
			'content'  => '',
			'notices'  => array(),
		);

		if ( ! $report['exists'] ) {
			$report['notices'][] = array( 'type' => 'info', 'message' => $this->missing_message( $key ) );
			return $report;
		}
		if ( ! $report['readable'] ) {
			$report['notices'][] = array( 'type' => 'warn', 'message' => __( 'The file exists but is not readable by WordPress.', 'tso-swiss-knife' ) );
			return $report;
		}
		if ( $report['size'] > 512 * 1024 ) {
			$report['notices'][] = array( 'type' => 'warn', 'message' => __( 'The file is larger than expected, so only metadata is reviewed.', 'tso-swiss-knife' ) );
			return $report;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$content = file_get_contents( $path );
		if ( false === $content ) {
			$report['notices'][] = array( 'type' => 'warn', 'message' => __( 'The file could not be read.', 'tso-swiss-knife' ) );
			return $report;
		}

		$report['content'] = $content;
		$report['notices'] = array_merge(
			$report['notices'],
			str_starts_with( $key, 'robots' ) ? $this->review_robots( $content ) : $this->review_htaccess( $content )
		);

		if ( $report['writable'] ) {
			$report['notices'][] = array( 'type' => 'info', 'message' => __( 'The file is writable by WordPress. You can edit it from this panel.', 'tso-swiss-knife' ) );
		}

		if ( empty( array_filter( $report['notices'], fn( $n ) => in_array( $n['type'], array( 'warn', 'error' ), true ) ) ) ) {
			$report['notices'][] = array( 'type' => 'ok', 'message' => __( 'No obvious issues were detected.', 'tso-swiss-knife' ) );
		}

		return $report;
	}

	private function missing_message( string $key ): string {
		if ( str_starts_with( $key, 'robots' ) ) {
			return __( 'No robots.txt file was found. WordPress may serve a default virtual robots.txt. You can create one here.', 'tso-swiss-knife' );
		}
		return __( 'No .htaccess file was found at the WordPress root. This is normal on Nginx servers. On Apache, it is required for pretty permalinks.', 'tso-swiss-knife' );
	}

	private function review_robots( string $content ): array {
		$notices = array();
		$lines   = $this->active_lines( $content );
		$text    = implode( "\n", $lines );

		if ( '' === trim( $text ) ) {
			$notices[] = array( 'type' => 'warn', 'message' => __( 'robots.txt has no active directives.', 'tso-swiss-knife' ) );
			return $notices;
		}
		if ( ! preg_match( '/^User-agent\s*:/im', $text ) ) {
			$notices[] = array( 'type' => 'warn', 'message' => __( 'No User-agent directive was found.', 'tso-swiss-knife' ) );
		}
		if ( preg_match( '/^Disallow\s*:\s*\/\s*$/im', $text ) ) {
			$notices[] = array( 'type' => 'warn', 'message' => __( 'A Disallow: / rule blocks crawling for the matching user agent.', 'tso-swiss-knife' ) );
		}
		if ( ! preg_match( '/^Sitemap\s*:/im', $text ) ) {
			$notices[] = array( 'type' => 'info', 'message' => __( 'No Sitemap directive was found. Consider adding one so search engines can discover your sitemap directly.', 'tso-swiss-knife' ) );
		}
		if ( preg_match( '/^Disallow\s*:\s*\/wp-content\/uploads/im', $text ) ) {
			$notices[] = array( 'type' => 'info', 'message' => __( 'Uploads are blocked for crawlers. Confirm this is intentional if media files should rank in search.', 'tso-swiss-knife' ) );
		}
		return $notices;
	}

	private function review_htaccess( string $content ): array {
		$notices = array();
		if ( false === strpos( $content, '# BEGIN WordPress' ) ) {
			$notices[] = array( 'type' => 'info', 'message' => __( 'The standard WordPress block was not found. This is normal with custom server rules.', 'tso-swiss-knife' ) );
		}
		if ( ! preg_match( '/^\s*RewriteEngine\s+On/im', $content ) ) {
			$notices[] = array( 'type' => 'warn', 'message' => __( 'RewriteEngine On was not found. Pretty permalinks may not work on Apache.', 'tso-swiss-knife' ) );
		}
		if ( preg_match( '/^\s*Options\s+\+Indexes/im', $content ) ) {
			$notices[] = array( 'type' => 'warn', 'message' => __( 'Directory indexing appears to be enabled (Options +Indexes). This shows folder contents to visitors.', 'tso-swiss-knife' ) );
		}
		if ( preg_match( '/wp-config\.php/im', $content ) ) {
			$notices[] = array( 'type' => 'ok', 'message' => __( 'A wp-config.php protection rule was found.', 'tso-swiss-knife' ) );
		} else {
			$notices[] = array( 'type' => 'info', 'message' => __( 'No explicit wp-config.php protection rule was found in this file.', 'tso-swiss-knife' ) );
		}
		return $notices;
	}

	private function active_lines( string $content ): array {
		$lines = preg_split( '/\R/', $content );
		if ( ! is_array( $lines ) ) { return array(); }
		return array_values( array_filter( array_map( 'trim', $lines ), static function ( string $line ): bool {
			return '' !== $line && 0 !== strpos( $line, '#' );
		} ) );
	}

	private function render_report( string $key, array $report, string $nonce ): void {
		$is_root     = ! empty( $report['is_root'] );
		$root_note   = ! empty( $report['root_note'] );
		$is_htaccess = ! empty( $report['is_htaccess'] );
		?>
		<div class="tsosk-card">
			<h3><?php echo esc_html( $report['label'] ); ?>
				<?php if ( $report['exists'] ) : ?>
				<span class="tsosk-badge tsosk-badge-ok" style="font-size:12px;margin-left:8px;"><?php esc_html_e( 'Found', 'tso-swiss-knife' ); ?></span>
				<?php else : ?>
				<span class="tsosk-badge tsosk-badge-info" style="font-size:12px;margin-left:8px;"><?php esc_html_e( 'Not found', 'tso-swiss-knife' ); ?></span>
				<?php endif; ?>
			</h3>

			<?php if ( $is_root && ! $is_htaccess ) : ?>
			<div class="tsosk-notice tsosk-notice-info">
				<strong><?php esc_html_e( '🌐 This is the file Google reads.', 'tso-swiss-knife' ); ?></strong>
				<?php esc_html_e( 'Search engines (Google, Bing, etc.) always look for robots.txt at the domain root — for example https://example.com/robots.txt. If your WordPress is installed in a subdirectory like /blog/ or /pruebas/, the search engines still only read the one at the root domain. Rules in this file apply to the entire domain and all its subdirectories.', 'tso-swiss-knife' ); ?>
			</div>
			<?php elseif ( $is_root && $is_htaccess ) : ?>
			<div class="tsosk-notice tsosk-notice-info">
				<strong><?php esc_html_e( 'Document root .htaccess', 'tso-swiss-knife' ); ?></strong>
				<?php esc_html_e( 'This is the .htaccess at your hosting document root (e.g. public_html). It may contain site-wide redirects, security rules or PHP settings that apply before WordPress loads. The WordPress subdirectory has its own .htaccess below for permalinks.', 'tso-swiss-knife' ); ?>
			</div>
			<?php elseif ( $root_note && $is_htaccess ) : ?>
			<div class="tsosk-notice tsosk-notice-warn">
				<strong><?php esc_html_e( 'WordPress permalink .htaccess', 'tso-swiss-knife' ); ?></strong>
				<?php esc_html_e( 'This file only affects URLs inside the WordPress folder. Pretty permalinks and rewrite rules for posts/pages are stored here. Site-wide rules in public_html/.htaccess are shown separately above when detected.', 'tso-swiss-knife' ); ?>
			</div>
			<?php elseif ( $root_note ) : ?>
			<div class="tsosk-notice tsosk-notice-warn">
				<strong><?php esc_html_e( '⚠ Google does not read this file.', 'tso-swiss-knife' ); ?></strong>
				<?php esc_html_e( 'This robots.txt is inside a WordPress subdirectory. Search engines ignore it — they only read the one at the domain root. You can edit it here for your own reference, but it has no effect on how crawlers index your site.', 'tso-swiss-knife' ); ?>
			</div>
			<?php endif; ?>

			<table class="tsosk-kv-table" style="margin-bottom:12px;">
				<tr>
					<th style="width:120px;"><?php esc_html_e( 'Path', 'tso-swiss-knife' ); ?></th>
					<td><code><?php echo esc_html( $report['path'] ); ?></code></td>
				</tr>
				<?php if ( $report['exists'] ) : ?>
				<tr>
					<th><?php esc_html_e( 'Size', 'tso-swiss-knife' ); ?></th>
					<td><?php echo esc_html( size_format( (int) $report['size'], 2 ) ); ?></td>
				</tr>
				<tr>
					<th><?php esc_html_e( 'Modified', 'tso-swiss-knife' ); ?></th>
					<td><?php echo $report['modified'] ? esc_html( date_i18n( 'Y-m-d H:i', (int) $report['modified'] ) ) : '—'; ?></td>
				</tr>
				<?php endif; ?>
			</table>

			<ul class="tsosk-review-list">
				<?php foreach ( $report['notices'] as $notice ) : ?>
				<li>
					<span class="tsosk-badge <?php echo esc_attr( $this->badge_class( $notice['type'] ) ); ?>"><?php echo esc_html( strtoupper( $notice['type'] ) ); ?></span>
					<?php echo esc_html( $notice['message'] ); ?>
				</li>
				<?php endforeach; ?>
			</ul>

			<?php if ( '' !== $report['content'] || ! $report['exists'] ) : ?>
			<details open style="margin-top:12px;">
				<summary style="cursor:pointer;font-weight:600;margin-bottom:8px;">
					<?php esc_html_e( 'File contents', 'tso-swiss-knife' ); ?>
					<?php if ( $report['writable'] || ( ! $report['exists'] && wp_is_writable( dirname( $report['path'] ) ) ) ) : ?>
					<span class="tsosk-badge tsosk-badge-info" style="font-size:11px;margin-left:6px;"><?php esc_html_e( 'Editable', 'tso-swiss-knife' ); ?></span>
					<?php endif; ?>
				</summary>
				<textarea id="tsosk-sf-content-<?php echo esc_attr( $key ); ?>"
				          style="width:100%;min-height:220px;font-family:monospace;font-size:12px;resize:vertical;box-sizing:border-box;"
				          spellcheck="false"><?php echo esc_textarea( $report['content'] ); ?></textarea>
				<?php if ( $report['writable'] || ( ! $report['exists'] && wp_is_writable( dirname( $report['path'] ) ) ) ) : ?>
				<div style="margin-top:8px;display:flex;gap:8px;align-items:center;">
					<button class="button button-primary tsosk-sf-save"
					        data-key="<?php echo esc_attr( $key ); ?>"
					        data-nonce="<?php echo esc_attr( $nonce ); ?>">
						<?php esc_html_e( 'Save Changes', 'tso-swiss-knife' ); ?>
					</button>
					<span class="tsosk-ajax-msg tsosk-sf-msg-<?php echo esc_attr( $key ); ?>"></span>
				</div>
				<?php else : ?>
				<p class="description"><?php esc_html_e( 'File is read-only. To edit it, make it writable via FTP or your hosting control panel.', 'tso-swiss-knife' ); ?></p>
				<?php endif; ?>
			</details>
			<?php endif; ?>
		</div>
		<?php
	}

	private function badge_class( string $type ): string {
		if ( 'warn' === $type )  { return 'tsosk-badge-warn'; }
		if ( 'ok' === $type )    { return 'tsosk-badge-ok'; }
		if ( 'error' === $type ) { return 'tsosk-badge-warn'; }
		return 'tsosk-badge-info';
	}
}
